# Path
path: '/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/go/bin:{{ user_directory }}/go/bin'

# Avalanche ports
avalanche_p2p_port: 9651

# Binance ports
binance_p2p_port: 40303
binance_http_port: 18545
binance_ws_port: 18546

# Celo ports
celo_p2p_port: 20303
celo_http_port: 28545

# Ethereum ports
geth_p2p_port: 30303
geth_http_port: 8545

# Fantom ports
fantom_p2p_port: 5050

# Moonbeam ports
moonbeam_p2p_port: 30333

# Polygon ports
bor_p2p_port: 31303
bor_http_port: 38545

# Filecoin ports
filecoin_p2p_port: 32303
filecoin_http_port: 1234