---
binance_repository: 'https://github.com/bnb-chain/bsc'
binance_directory: '{{ user_directory }}/binance'
binance_data_directory: '{{ user_directory }}/.binance'
binance_version: v1.1.17
binance_p2p_port: 40303
