---
- name: Open p2p port
  become: true
  ufw:
    rule: allow
    proto: tcp
    port: '{{ geth_p2p_port }}'

- name: Restart Nodes
  become: true
  systemd:
    name: '{{ item }}'
    daemon_reload: true
    state: restarted
    enabled: true
  loop:
    - prysm
    - geth
