---
- name: download Fantom genesis file
  get_url:
    url: 'https://download.fantom.network/{{ fantom_genesis }}'
    dest: '{{ fantom_data_directory }}'
    mode: '0700'

- name: Copy Fantom systemd file
  become: true
  template:
    src: 'fantom.service.j2'
    dest: '/etc/systemd/system/fantom.service'
    owner: root
    group: root
    mode: '0644'

- name: Open p2p port
  become: true
  ufw:
    rule: allow
    proto: tcp
    port: '{{ fantom_p2p_port }}'
