---
- name: Clone Fantom repo
  git:
    repo: '{{ fantom_repository }}'
    dest: '{{ fantom_directory }}'
    version: '{{ fantom_version }}'
    update: yes
    force: yes
    recursive: no

- name: Install Fantom
  command: '{{ item }}'
  args:
    chdir: '{{ fantom_directory }}'
  with_items:
    - 'make'

- name: Copy Fantom binary
  become: true
  copy:
    remote_src: true
    src: '{{ fantom_directory }}/build/opera'
    dest: '/usr/bin/opera'
    mode: '0755'

- name: Restart Nodes
  become: true
  systemd:
    name: '{{ item }}'
    daemon_reload: true
    state: restarted
    enabled: true
  loop:
    - fantom
