---
- name: Install dependencies
  become: true
  apt:
    name:
      - gnupg
      - libusb
    state: present
    update_cache: true

- name: get linux distribution
  command: 'lsb_release -s -c'
  register: distribution

- name: add NodeSource GPG key
  become: true
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add NodeSource repo
  become: true
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ distribution.stdout }} main'
    state: present

- name: add yarn GPG key
  become: true
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: Add yarn repo
  become: true
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian stable main
    state: present

- name: Install nodejs and yarn
  become: true
  apt:
    name:
      - nodejs
      - yarn
    state: latest
    update_cache: true

- name: Clone arbitrum repo
  git:
    repo: '{{ arbitrum_repo }}'
    dest: '{{ arbitrum_directory }}'
    version: '{{ arbitrum_version }}'
    update: true
    force: true
    recursive: false

- name: Install arbitrum
  become: true
  command: 'yarn'
  args:
    chdir: '{{ arbitrum_directory }}'
