---
- name: download moonbeam binary
  get_url:
    url: 'https://github.com/PureStake/moonbeam/releases/download/{{ moonbeam_version }}/moonbeam'
    dest: '{{ moonbeam_node_directory }}'
    mode: '0700'

- name: Restart Nodes
  become: true
  systemd:
    name: '{{ item }}'
    daemon_reload: true
    state: restarted
    enabled: true
  loop:
    - moonbeam
