---
# - name: Heimdall
#   import_tasks: heimdall.yml
#   when: mode is defined and mode == "full"
# - name: Bor
#   import_tasks: bor.yml
#   when: mode is defined and mode == "full"
# - name: Setup Networks
#   import_tasks: setup_networks.yml
#   when: mode is defined and mode == "full"
# - name: Setup Services
#   import_tasks: setup_services.yml
#   when: mode is defined and mode == "full"
- name: Setup Configs
  import_tasks: setup_configs.yml
  when: mode is defined and mode == "full"
