---
- name: Create metadata folder
  become: true
  file:
    path: '/etc/matic'
    state: directory
    mode: '0777'

- name: Generate metadata file
  copy:
    content: 'VALIDATOR_ADDRESS='
    dest: /etc/matic/metadata
    mode: '0777'

- name: Copy all service files
  become: true
  template:
    src: '{{ item }}.service.j2'
    dest: '/etc/systemd/system/{{ item }}.service'
    owner: root
    group: root
    mode: '0644'
  loop:
    - heimdalld
    - heimdalld-rest-server
    - bor
